USE [master]
GO

/****** Object:  Database [Gym ]    Script Date: 1/19/2019 12:01:08 AM ******/
CREATE DATABASE [Gym ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Gym', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Gym .mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Gym _log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Gym _log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Gym ] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Gym ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Gym ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Gym ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Gym ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Gym ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Gym ] SET ARITHABORT OFF 
GO

ALTER DATABASE [Gym ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Gym ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Gym ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Gym ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Gym ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Gym ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Gym ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Gym ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Gym ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Gym ] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Gym ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Gym ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Gym ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Gym ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Gym ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Gym ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Gym ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Gym ] SET RECOVERY FULL 
GO

ALTER DATABASE [Gym ] SET  MULTI_USER 
GO

ALTER DATABASE [Gym ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Gym ] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Gym ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Gym ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Gym ] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Gym ] SET QUERY_STORE = OFF
GO

USE [Gym ]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Gym ] SET  READ_WRITE 
GO


